projects = {}

# ここはお好みで。常に確認を取りたいなら "untrusted" が実務的です
approval_policy = "untrusted"

# 既定の read-only を上書きし、作業ディレクトリ内での実行を許可
sandbox_mode = "workspace-write"
model = "gpt-5-codex"
model_reasoning_effort = "high"

[sandbox_workspace_write]
# サンドボックス内のネットワークを有効化（既定は false）
network_access = true

web_search_request = "true"

safeCommands = [
  "ls",
  "rg",
  "rg -n",
  "rg --files",
  "nl",
  "nl -ba",
  "sed",
  "awk",
  "gh",
  "bash",
  "jq"
]

