require('plugins')
require('basic')
require('indent')

require('rc.bufferline')
require('rc.lualine')
require('rc.lsp')
require('rc.telescope')
require('rc.lspkind')
require('rc.nvim-cmp')
require('rc.lspsaga')
require('rc.trobule')
require('rc.treesitter')
require('rc.comment')
require('rc.nvim-navic')
require('rc.fuzzy-motion')
require('rc.ctags')
